### ISSUE TITLE
Cannot detect microbit

### ISSUE THREAD

**Issue by ashmitiscodingpython** [janickr/kaspersmicrobit#7]
When I try running the given program (in this link: https://kaspersmicrobit.readthedocs.io/en/stable/), I get an error like this:
"kaspersmicrobit.errors.BluetoothServiceNotFound: Could not find the service Service.BUTTON (uuid=e95d9882-251d-470a-a062-fa1922dfa9a8)
The available services on this micro:bit are:
  - Generic Access Profile         (Service.GENERIC_ACCESS      uuid=00001800-0000-1000-8000-00805f9b34fb)
  - Generic Attribute Profile      (Service.GENERIC_ATTRIBUTE   uuid=00001801-0000-1000-8000-00805f9b34fb)
  - Nordic Semiconductor ASA       (None                        uuid=0000fe59-0000-1000-8000-00805f9b34fb)
  - Unknown                        (None                        uuid=e97dd91d-251d-470a-a062-fa1922dfa9a8)
  - Device Information             (Service.DEVICE_INFORMATION  uuid=0000180a-0000-1000-8000-00805f9b34fb)
  - MicroBit Event Service         (Service.EVENT               uuid=e95d93af-251d-470a-a062-fa1922dfa9a8)

Is this micro:bit loaded with the correct ".hex" file?"
I have the correct hex file and my microbit does get paired but, for some reason, it's not able to detect any services. Can anyone help me?

**Comment by janickr** [comment]
This means that the hex file that is loaded on your microbit does not have the Bluetooth button service activated.

The program from "Getting started" https://kaspersmicrobit.readthedocs.io/en/stable/ you mentioned tries to connect to the bluetooth button service. If you follow the "Getting started" instructions, there is a link to a hex file that activates the button service, and this works without pairing the microbit. (if you try this, remove the microbit from the paired devices in your operating system first)

I assume  the hex file you loaded onto you microbit did not come from the kaspersmicrobit site?

If you want to create your own hex files (with makecode) or if you want "JustWorks pairing" instead of "no pairing required", first  take a few moments to read all about bluetooth and the microbit here: https://kaspersmicrobit.readthedocs.io/en/stable/makecode-bluetooth/enable-bluetooth/  (also click on the "With pairing" and "Without pairing" sections in the navigation on the left)

There is also a convenient testing script https://kaspersmicrobit.readthedocs.io/en/stable/test-all-services/  which prints the active services on your microbit and tries to connect with them.

**Comment by ashmitiscodingpython** [comment]
I have read the whole documentation and your comment and I have taken the hex program directly from your site but it doesn't seem to resolve the problem.

**Comment by janickr** [comment]
which hex file did you use?

**Comment by ashmitiscodingpython** [comment]
The one from your site.

**Comment by ashmitiscodingpython** [comment]
The "Getting Started" one.

**Comment by janickr** [comment]
Can you try this one, and tell me what number is displayed on the microbit led screen:
https://kaspersmicrobit.readthedocs.io/en/stable/assets/hex/issue/microbit-issue-7.hex

**Comment by ashmitiscodingpython** [comment]
I think it's showing 33

**Comment by ashmitiscodingpython** [comment]
It's showing:
# #   # #
   #      #
# #   # #
   #       #
# #   # #

**Comment by janickr** [comment]
And does the example from https://kaspersmicrobit.readthedocs.io/en/stable/ work with this hex file?

**Comment by ashmitiscodingpython** [comment]
No it doesn't

**Comment by janickr** [comment]
What is the output?

**Comment by ashmitiscodingpython** [comment]
The same as before.

**Comment by janickr** [comment]
Can you run the example here please: https://kaspersmicrobit.readthedocs.io/en/stable/test-all-services/
And paste the output, thanks!

**Comment by ashmitiscodingpython** [comment]
Platform: Windows-10-10.0.22631-SP0
Python version: 3.10.3

Bluetooth address: EE:86:67:65:CD:32

Service.GENERIC_ACCESS available
Traceback (most recent call last):
  File "C:\Users\Saritha\PycharmProjects\MicrobitCommunication\venv\Main.py", line 15, in <module>
    print(f"Device name: {microbit.generic_access.read_device_name()}")
  File "C:\Users\Saritha\PycharmProjects\MicrobitCommunication\venv\lib\site-packages\kaspersmicrobit\services\generic_access.py", line 40, in read_device_name
    return str(self._device.read(Service.GENERIC_ACCESS, Characteristic.DEVICE_NAME), "utf-8")
  File "C:\Users\Saritha\PycharmProjects\MicrobitCommunication\venv\lib\site-packages\kaspersmicrobit\bluetoothdevice.py", line 90, in read
    result = self._loop.run_async(self._client.read_gatt_char(gatt_characteristic)).result()
  File "C:\Users\Saritha\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 446, in result
    return self.__get_result()
  File "C:\Users\Saritha\AppData\Local\Programs\Python\Python310\lib\concurrent\futures\_base.py", line 391, in __get_result
    raise self._exception
  File "C:\Users\Saritha\PycharmProjects\MicrobitCommunication\venv\lib\site-packages\bleak\__init__.py", line 711, in read_gatt_char
    return await self._backend.read_gatt_char(char_specifier, **kwargs)
  File "C:\Users\Saritha\PycharmProjects\MicrobitCommunication\venv\lib\site-packages\bleak\backends\winrt\client.py", line 826, in read_gatt_char
    _ensure_success(
  File "C:\Users\Saritha\PycharmProjects\MicrobitCommunication\venv\lib\site-packages\bleak\backends\winrt\client.py", line 163, in _ensure_success
    raise BleakError(f"{fail_msg}: Unreachable")
bleak.exc.BleakError: Could not read characteristic handle 2: Unreachable

Process finished with exit code 1

**Comment by janickr** [comment]
Are there other microbits in the room that have bluetooth enabled?

**Comment by ashmitiscodingpython** [comment]
No

**Comment by janickr** [comment]
Is your microbit paired with windows?

**Comment by ashmitiscodingpython** [comment]
Yeah

**Comment by janickr** [comment]
Can you remove the microbit from the paired devices please.
Both the hex file from "Getting started" and the one displaying the number 33 are in the mode of "No pairing required"

Those hex files will not work if your microbit is paired with windows.

**Comment by ashmitiscodingpython** [comment]
It worked! Thank you!

**Comment by janickr** [comment]
Fantastic! Have fun!

**Comment by ashmitiscodingpython** [comment]
Now it can't detect my microbit. Only when I put it into bluetooth pairing mode it works.

**Comment by janickr** [comment]
What is the difference between this attempt and the last time it worked?

**Comment by ashmitiscodingpython** [comment]
Well, now it CAN detect the services but it's not detecting the microbit itself except when it's in bluetooth pairing mode

**Comment by janickr** [comment]
Sorry I don´t get what you mean by "it doesn´t detect the microbit itself" Can you give an example or a screenshot?

**Comment by ashmitiscodingpython** [comment]
kaspersmicrobit.errors.KaspersMicrobitNotFound: Could not find the micro:bit with name "None"

**Comment by janickr** [comment]
Is this another hex file?

**Comment by ashmitiscodingpython** [comment]
Yes
![image](https://github.com/janickr/kaspersmicrobit/assets/96191275/047d1f49-4b60-4941-89be-f444ba0c6992)

**Comment by janickr** [comment]
Probably your project has the "JustWorks Pairing" mode enabled. You need to enable "No Pairing Required" in the settings:
https://kaspersmicrobit.readthedocs.io/en/stable/makecode-bluetooth/create-a-makecode-project-without-pairing/#disable-pairing
(Disable the event service while you're there, you probably don't need it)

I urge you to carefully read the documentation on the site. Everything is explained there: the preference for "No pairing required", and how to disable or enable pairing.

By the way it's best to enable only the services you need (this is especially important if you have a microbit v1)

**Comment by ashmitiscodingpython** [comment]
First of all I would like to say that I HAVE read the documentation very very carefully, every single word. Second, I didn't make the mistake of not enabling 'No Pairing Required'. But, now it works. I really don't know what was the problem. I just disabled the event service and, for some reason, it now works. Anyways, thank you for your support. I really am very grateful to you.

**Comment by ashmitiscodingpython** [comment]
I don't know why but it still says that Event service is enabled.

**Comment by janickr** [comment]
Thanks for the appreciation! And for reading the docs!  Have fun!!!!
