### ISSUE TITLE
io_pin : can you explain how to read/write to 1 particular pin?

### ISSUE THREAD

**Issue by idef1x** [janickr/kaspersmicrobit#8]
The example microbit-io_pin.py works fine, but reads all defined input ports. How can I read the value of 1 port i.e:  Pin1?

Same for writing data to an output port. Say I have a led on pin0, which I configured as a digital output port. How would I write exactly to this pin0?

I am a total noob in python, so might be the reason why I can't figure this out ;-)

**Comment by janickr** [comment]
Hi @idef1x, no worries I'm happy to help

Writing a to a single pin is supported: you can supply a list containing only one pin value, like this:
```python
# wrapping the PinValue in [ ] creates a list
microbit.io_pin.write_data([PinValue(Pin.P1, 1)])
```

The bluetooth io pin service in the [microbit bluetooth profile](https://lancaster-university.github.io/microbit-docs/resources/bluetooth/bluetooth_profile.html) defines the result of the read operation to return the values for all input pins. Kaspersmicrobit cannot change that. 

If you define a function which looks for the pin in the list and returns the value if it exists:
```python
def pin_value(pin, values):
    return next((v.value for v in values if v.pin == pin), None)
```
Then you can select the value of a single pin:
```python
value_of_p1 = pin_value(Pin.P1, your_microbit.io_pin.read_data())
```

An alternative could be a function to create a dict from the list of values:
```python
from collections import defaultdict

def to_dict(values):
    return defaultdict(lambda:None, {p.pin: p.value for p in values})
```
this can help you access values from different pins:
```python
pin_values = to_dict(your_microbit.io_pin.read_data())
value_of_p1 = pin_values[Pin.P1] 
value_of_p5 = pin_values[Pin.P5] 
```

Maybe I'll also include a function like this in a next release of Kaspersmicrobit .

**Comment by idef1x** [comment]
Hi @janickr ,

Thanks for your swift response! Will try it out after the weekend as it's to sunny atm here in the Netherlands ;-)
Will let you know if I succeed :-)

**Comment by idef1x** [comment]
Hi @janickr ,
It works now! Thanks for your support :)
